### ISSUE TITLE
Port to newer GTK?

### ISSUE THREAD

**Issue by petterreinholdtsen** [muflone/bluewho#4]
The bluewho package has been removed from Debian because it was unmaintained and depended on gtk 2, as can be seen on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945617 and https://tracker.debian.org/bluewho .  Is there any chance to have it ported to gtk 3?  I notice there is a patch for that in https://github.com/mmfrank/bluewho/commits/master , perhaps these could be included here as well?

**Comment by muflone** [comment]
Hi
BlueWho was just ported to Python 3 + GTK+ >= 3.10

I don't plan to support GTK+ 4 actually, maybe in the future
Feel free to test the newer version from git.
